### PR TITLE
Just some minor doc edits for clarity

### PR DESCRIPTION
**Pull request by dnmfarrell**

### CODE REVIEW

**Comment by xsawyerx** [comment]
Cherry-picked. Thanks! :+1:

**Comment by xsawyerx** [comment]
https://github.com/xsawyerx/xs-fun/commit/d74fbed0676e1e0750f05c79a0a215b977734ed1
https://github.com/xsawyerx/xs-fun/commit/517b051a7ad76e97034cb5e9748ab11dc254a47a

**Comment by dnmfarrell** [comment]
I thought it would never happen!!

**Comment by xsawyerx** [comment]
I'm sorry. :(

I didn't see the notifications about these.

**Pull request closed without merging**
