### PR TITLE
General edits of current text

### PR DESCRIPTION
**Pull request by paultcochrane**
Here are some basic edits of the current text to improve overall formatting and style consistency.

Comments welcome!

### CODE REVIEW

**Comment by xsawyerx** [comment]
@paultcochrane Other than the chunk at the end, these all seem like it's just pushing a word from the beginning of one line to the end of the previous one. Is that really necessary? Did you run this through some automated formatter that forced to put more words on the line?

**Comment by paultcochrane** [comment]
@xsawyerx the last commit (e3f2d24) simply wraps the text to 80 char width.  You can leave that one out if you want, as it's basically just a cosmetic change.  I often find it's nice to have consistently wrapped paragraphs when reading a text, but that's just me being pedantic I guess :-)

To wrap the paragraphs, I used the `gqip` command in vim.

**Comment by xsawyerx** [comment]
Everything except the last commit has been merged. Thanks @paultcochrane. Would you like a commit bit?

**Comment by paultcochrane** [comment]
Sure!  Go for it :-)

**Comment by xsawyerx** [comment]
@paultcochrane, done! Please feel *free* to just push all the changes you see fit. No need to go through me. :)

**Comment by paultcochrane** [comment]
muwahaha!  ;-)

**Comment by paultcochrane** [comment]
erm, I meant, awesome!  Thanks!  :-)

**Pull request closed without merging**
